<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="customer.aspx.cs" Inherits="Assignment.customer" EnableEventValidation="False" ValidateRequest="False" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 175px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="than">
        <div id="left">
            <div style="border-radius: 5px; border: 1px solid #090;padding:5px">
    	     	<H3>Thêm Khách Hàng</H3>
                <form method="post">
                    <table style="width:100%;">
                        <tr>
                            <td class="auto-style1"><label for="customID">Mã Khách hàng:</label></td>
                            <td>
                                <asp:TextBox ID="makhachhang" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" ></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Tên Khách hàng:</td>
                            <td>
                                <asp:TextBox ID="tenkhachhang" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Số điện thoại:</td>
                            <td>
                                <asp:TextBox ID="sodienthoai" runat="server" Width="50%" type="number" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"> Địa Chỉ:</td>
                            <td>
                                <asp:TextBox ID="address" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Ngày Sinh:</td>
                            <td>
                                <asp:TextBox ID="birthofyear" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" type="Date"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"></td>
                            <td>
                                
                                <asp:ImageButton ID="themkhachhang" runat="server" Height="40px" ImageUrl="~/images/GreenRoundedButton.png" OnClick="ImageButton1_Click" Width="150px" />
                                
                            </td>
                        </tr>
                    </table>
                </form>
                <div>
                    <asp:GridView ID="grvkhachhang" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" Width="100%" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="grvkhachhang_RowCancelingEdit" OnRowDataBound="grvkhachhang_RowDataBound" OnRowDeleting="grvkhachhang_RowDeleting" OnRowEditing="grvkhachhang_RowEditing" OnRowUpdating="grvkhachhang_RowUpdating" AutoGenerateColumns="False" >
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="CustomerID" HeaderText="Mã Khách Hàng" ReadOnly="True" />
                            <asp:BoundField DataField="Ten" HeaderText="Tên Khách Hàng" />
                            <asp:BoundField DataField="DienThoai" HeaderText="Điện Thoại" />
                            <asp:BoundField DataField="DiaChi" HeaderText="Địa Chỉ" />
                            <asp:BoundField DataField="NgaySinh" HeaderText="Ngày Sinh" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
