<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="hoadonchitiet.aspx.cs" Inherits="Assignment.hoadonchitiet" EnableEventValidation="False" ValidateRequest="False" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 175px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="than">
        <div id="left">
            <div style="border-radius: 5px; border: 1px solid #090;padding:5px">
                <H3>Thêm Hóa đơn chi tiết</H3>
                <form method="post">
                    <table style="width:100%;">
                        <tr>
                            <td class="auto-style1"><label for="customID">Mã Hóa Đơn</label></td>
                            <td>
                                <asp:DropDownList ID="mahoadonlist" runat="server" DataSourceID="SqlDatamahd" DataTextField="MaHD" DataValueField="MaHD">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDatamahd" runat="server" ConnectionString="<%$ ConnectionStrings:ASSIGNMENTConnection %>" SelectCommand="SELECT [MaHD] FROM [HoaDon]"></asp:SqlDataSource>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Mã Sản Phẩm</td>
                            <td>
                                <asp:DropDownList ID="masanphamlist" runat="server" DataSourceID="SqlDatamasp" DataTextField="MaSp" DataValueField="MaSp">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDatamasp" runat="server" ConnectionString="<%$ ConnectionStrings:ASSIGNMENTConnection %>" SelectCommand="SELECT [MaSp] FROM [SanPham]"></asp:SqlDataSource>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Số Lượng</td>
                            <td>
                                <asp:TextBox ID="soluong" runat="server" Width="50%" type="number" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"> Thành Tiền</td>
                            <td>
                                <asp:TextBox ID="tongtien" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" type="number"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Giảm Giá</td>
                            <td>
                                <asp:TextBox ID="giamgia" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" type="number"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"></td>
                            <td>
                                
                                <asp:ImageButton ID="themhoadonchitiet" runat="server" Height="40px" ImageUrl="~/images/GreenRoundedButton.png" OnClick="ImageButton1_Click" Width="150px" />
                                
                            </td>
                        </tr>
                    </table>
                </form>
                <div>

                    <asp:GridView ID="grvhoadonchitiet" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDataBound="GridView1_RowDataBound" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" Width="100%">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="MaHD" HeaderText="Mã Hóa Đơn" ReadOnly="True" />
                            <asp:BoundField DataField="MaSp" HeaderText="Mã Sản Phẩm" ReadOnly="True" />
                            <asp:BoundField DataField="SoLuong" HeaderText="Số Lượng" />
                            <asp:BoundField DataField="ThanhTien" HeaderText="Thành Tiền" />
                            <asp:BoundField DataField="MucGiamGia" HeaderText="MucGiamGia" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>

                </div>
            </div>
        </div>
    </div>
</asp:Content>
