<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="hoadon.aspx.cs" Inherits="Assignment.hoadon" EnableEventValidation="False" ValidateRequest="False" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 175px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="than">
        <div id="left">
            <div style="border-radius: 5px; border: 1px solid #090;padding:5px">
                <H3>Thêm Hóa Đớn</H3>
                <form method="post">
                    <table style="width:100%;">
                        <tr>
                            <td class="auto-style1"><label for="customID">Mã Hóa Đơn</label></td>
                            <td>
                                <asp:TextBox ID="mahoadon" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" ></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Mã Khách Hàng</td>
                            <td>
                                <asp:DropDownList ID="makhachhanglist" runat="server" DataSourceID="SqlDatalist" DataTextField="CustomerID" DataValueField="CustomerID">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDatalist" runat="server" ConnectionString="<%$ ConnectionStrings:ASSIGNMENTConnection %>" SelectCommand="SELECT [CustomerID] FROM [KhachHang]"></asp:SqlDataSource>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Ngày Đặt Hàng</td>
                            <td>
                                <asp:TextBox ID="ngaydathang" runat="server" Width="50%" type="Date" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"> Mã Số Thuế</td>
                            <td>
                                <asp:TextBox ID="masothue" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" type="text"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Ngày Giao Hàng</td>
                            <td>
                                <asp:TextBox ID="ngaygiaohang" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" type="Date"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Nơi Giao Hàng</td>
                            <td>
                                <asp:TextBox ID="noigiaohang" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" ></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"></td>
                            <td>
                                
                                <asp:ImageButton ID="themhoadon" runat="server" Height="40px" ImageUrl="~/images/GreenRoundedButton.png" OnClick="ImageButton1_Click" Width="150px" />
                                
                            </td>
                        </tr>
                    </table>
                </form>
                <div>

                    <asp:GridView ID="grvhoadon" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDataBound="GridView1_RowDataBound" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" Width="100%">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="MaHD" HeaderText="Mã Hóa Đơn" ReadOnly="True" />
                            <asp:BoundField DataField="CustomerID" HeaderText="Mã Khách Hàng" />
                            <asp:BoundField DataField="NgayDatHang" HeaderText="Ngày Đặt Hàng" />
                            <asp:BoundField DataField="MaSoThue" HeaderText="Mã Số Thuế" />
                            <asp:BoundField DataField="NgayGiaoHang" HeaderText="Ngày Giao Hàng" />
                            <asp:BoundField DataField="NoiGiaoHang" HeaderText="Nơi Giao Hàng" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>

                </div>
            </div>
        </div>
    </div>
</asp:Content>
