<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="producs.aspx.cs" Inherits="Assignment.producs" EnableEventValidation="False" ValidateRequest="False" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 175px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="than">
        <div id="left">
            <div style="border-radius: 5px; border: 1px solid #090;padding:5px">
                <H3>Thêm Sản Phẩm</H3>
                <form method="post">
                    <table style="width:100%;">
                        <tr>
                            <td class="auto-style1"><label for="customID">Mã Sản Phẩm</label></td>
                            <td>
                                <asp:TextBox ID="masanpham" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" ></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Tên Sản Phẩm</td>
                            <td>
                                <asp:TextBox ID="tensanpham" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Giá Sản Phẩm</td>
                            <td>
                                <asp:TextBox ID="giasanpham" runat="server" Width="50%" type="number" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px" ></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"> Mã Nhà Sản Xuất</td>
                            <td>
                                <asp:TextBox ID="manhasanxuat" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Mã Loại Sản Phẩm</td>
                            <td>
                                <asp:DropDownList ID="maloaisanpham" runat="server" DataSourceID="SqlDataSource1" DataTextField="MaLoaiSp" DataValueField="MaLoaiSp">
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ASSIGNMENTConnection %>" SelectCommand="SELECT [MaLoaiSp] FROM [LoaiSanPham]"></asp:SqlDataSource>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Xuất Sứ Sản Phẩm</td>
                            <td>
                                <asp:TextBox ID="xuatsusanpham" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">Mô tả</td>
                            <td>
                                <asp:TextBox ID="motasanpham" runat="server" Width="50%" BorderColor="#009900" BorderStyle="Double" BorderWidth="1px"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1"></td>
                            <td>
                                
                                <asp:ImageButton ID="themsanpham" runat="server" Height="40px" ImageUrl="~/images/GreenRoundedButton.png" OnClick="ImageButton1_Click" Width="150px" />
                                
                            </td>
                        </tr>
                    </table>
                </form>
                <div>
                    <asp:GridView ID="grvsanpham" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDataBound="GridView1_RowDataBound" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" Width="100%">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="MaSp" HeaderText="Mã Sản Phẩm" ReadOnly="True" />
                            <asp:BoundField DataField="MaNhaSX" HeaderText="Mã Nhà SX" />
                            <asp:BoundField DataField="MaLoaiSp" HeaderText="Mã Loại SP" />
                            <asp:BoundField DataField="TenSp" HeaderText="Tên Sản Phẩm" />
                            <asp:BoundField DataField="GiaSp" HeaderText="Giá Sản Phẩm" />
                            <asp:BoundField DataField="MotaSp" HeaderText="Mô tả" />
                            <asp:BoundField DataField="XuatXuSp" HeaderText="Xuất Sứ" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
